export function Privacy() {
  return <article className="privacy-content">
    <h1>Privacy</h1>
    <p className="privacy-intro">Smallbin lets you share text and files without creating an account. Here is what happens to your data.</p>
    <section><h2>Your content is encrypted on your device.</h2><p>Your message, filenames, file types, and file contents are encrypted together in your browser using AES-256-GCM. The server receives encrypted bytes. Decryption happens in the recipient’s browser.</p><p>The decryption key is the part after <code>#</code> in your share link. Smallbin does not send this key to the server. Anyone with the complete link can read the bin, so share it carefully. Browser history, clipboard history, extensions, and software on your device may retain or access the link and content.</p></section>
    <section><h2>There is no tracking here.</h2><p>The app uses no analytics, advertising, cookies, external fonts, third-party services, or browser storage for your content and keys. QR codes are generated locally. The app does not log requests or their contents.</p><p>Your browser may store history or downloads independently. Hosting infrastructure, network providers, or a differently configured reverse proxy may also record connection information. This is privacy-respecting sharing, not a promise of complete anonymity.</p></section>
    <section><h2>The server can see some metadata.</h2><p>The server sees each bin’s random identifier, ciphertext size, creation and expiry times, and network activity. Your IP address is used during the connection and for temporary throttling.</p><p>Throttling identifiers are derived from IP addresses using a random process secret and kept in bounded, expiring memory. They are not saved in the database. The database keeps only bin identifiers, timestamps, and encrypted sizes.</p></section>
    <section><h2>Expiry stops new downloads.</h2><p>A bin’s lifetime starts after its upload completes. When it expires, the server stops new downloads and removes its stored files during cleanup, normally within a minute. A download already in progress may finish.</p><p>Expiry cannot revoke content already opened, copied, or downloaded. Deleting a file is not a guarantee of physical erasure from a storage device. Self-hosters should exclude bin data from backups and snapshots.</p></section>
    <section><h2>Your device and the app still need your trust.</h2><p>Browser encryption depends on the code delivered by this website and the security of your device. A compromised server or device can undermine that protection. Use HTTPS and keep your browser up to date.</p><p>Shared text is shown as plain text. Attachments are downloaded only when you choose to download them. Treat unfamiliar files with care when opening them in other applications.</p></section>
  </article>;
}
